# Generated by Django 5.2.2 on 2025-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0003_t001mai'),
    ]

    operations = [
        migrations.CreateModel(
            name='t001tes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susrlog', models.EmailField(help_text='Logins de Email', max_length=30, verbose_name='SUsrLog')),
            ],
        ),
    ]
