# Generated by Django 5.2.2 on 2025-06-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0004_t001tes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t001tes',
            table='"t"',
        ),
    ]
