# Generated by Django 5.2.2 on 2025-06-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0005_alter_t001tes_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t001tes',
        ),
    ]
