# Generated by Django 5.2.2 on 2025-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0007_delete_t001mai_alter_t001log_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t001log',
            name='susrnam',
            field=models.CharField(default='Null', help_text='Nome do Usuário', max_length=100, verbose_name='SUsrNam'),
        ),
        migrations.AddField(
            model_name='t001log',
            name='susrsen',
            field=models.CharField(default='Null', help_text='Senha do Usuário', max_length=100, verbose_name='SUsrSet'),
        ),
        migrations.AddField(
            model_name='t001log',
            name='susrset',
            field=models.CharField(default='Null', help_text='Setor do Usuário', max_length=100, verbose_name='SUsrSet'),
        ),
    ]
