# Generated by Django 5.2.2 on 2025-07-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0008_t001log_susrnam_t001log_susrsen_t001log_susrset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001log',
            name='susrsen',
            field=models.CharField(default='Null', help_text='Senha do Usuário', max_length=100, verbose_name='SUsrSen'),
        ),
    ]
