# Generated by Django 5.2.2 on 2025-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0009_alter_t001log_susrsen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001log',
            name='susrlog',
            field=models.EmailField(help_text='Logins de Email', max_length=100, verbose_name='SUsrLog'),
        ),
    ]
