# Generated by Django 5.2.2 on 2025-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0010_alter_t001log_susrlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='t010for',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nforcod', models.IntegerField(help_text='Codigo do Fornecedor', verbose_name='NForCod')),
                ('sfornam', models.CharField(help_text='Nome do Fornecedor', max_length=100, verbose_name='SForNam')),
                ('sforcnp', models.CharField(blank='True', help_text='CNPJ do Fornecedor', max_length=20, null='True', verbose_name='SForCnp')),
            ],
            options={
                'db_table': 't010for',
                'db_table_comment': 'Cadastro de Fornecedores',
            },
        ),
        migrations.AlterField(
            model_name='t001log',
            name='susrnam',
            field=models.CharField(blank='True', help_text='Nome do Usuário', max_length=100, null='True', verbose_name='SUsrNam'),
        ),
        migrations.AlterField(
            model_name='t001log',
            name='susrsen',
            field=models.CharField(blank='True', help_text='Senha do Usuário', max_length=100, null='True', verbose_name='SUsrSen'),
        ),
        migrations.AlterField(
            model_name='t001log',
            name='susrset',
            field=models.CharField(blank='True', help_text='Setor do Usuário', max_length=100, null='True', verbose_name='SUsrSet'),
        ),
    ]
