# Generated by Django 5.2.2 on 2025-07-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0011_t010for_alter_t001log_susrnam_alter_t001log_susrsen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='t100lic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncodlic', models.IntegerField(help_text='Código da Licença', verbose_name='NCodLic')),
                ('ssigite', models.CharField(help_text='Sigla da Licença', max_length=20, verbose_name='SSigIte')),
                ('ssetlic', models.CharField(help_text='Setor da Licença', max_length=100, verbose_name='SSetLic')),
                ('ddatini', models.DateField(help_text='Data de Inicio da Licença', verbose_name='DDatIni')),
                ('ddatfin', models.DateField(help_text='Data de Fim da Licença', verbose_name='DDatFin')),
                ('fdurlic', models.FloatField(help_text='Duração da Licença', verbose_name='FDurLic')),
                ('ssernum', models.CharField(help_text='Serial Number da Licença', max_length=200, verbose_name='SSerNum')),
                ('slinsit', models.CharField(help_text='Site da Licença', max_length=500, verbose_name='SLinSit')),
                ('susrcre', models.CharField(help_text='Credencial de acesso', max_length=100, verbose_name='SUsrCre')),
                ('ssencre', models.CharField(help_text='Senha de acesso', max_length=100, verbose_name='SSenCre')),
                ('ssetres', models.CharField(help_text='Setor responsavel pela renovação', max_length=100, verbose_name='SSetRes')),
                ('sobsadi', models.TextField(help_text='Observação Adicional', max_length=1000, verbose_name='SObsAdi')),
                ('ssitlic', models.CharField(help_text='Situação da Licença', max_length=20, verbose_name='SSitLic')),
            ],
            options={
                'db_table': 't100lic',
                'db_table_comment': 'Cadastro de Licenças',
            },
        ),
        migrations.AlterField(
            model_name='t010for',
            name='sforcnp',
            field=models.CharField(blank=True, help_text='CNPJ do Fornecedor', max_length=20, null=True, verbose_name='SForCnp'),
        ),
    ]
