# Generated by Django 5.2.2 on 2025-07-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0012_t100lic_alter_t010for_sforcnp'),
    ]

    operations = [
        migrations.AddField(
            model_name='t100lic',
            name='snomlic',
            field=models.CharField(default='null', help_text='Nome da Licença', max_length=100, verbose_name='SNomLic'),
        ),
    ]
