# Generated by Django 5.2.2 on 2025-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0013_t100lic_snomlic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t100lic',
            name='snomlic',
            field=models.CharField(help_text='Nome da Licença', max_length=100, verbose_name='SNomLic'),
        ),
    ]
