# Generated by Django 5.2.2 on 2025-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0014_alter_t100lic_snomlic'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonResponseMaxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
