# Generated by Django 5.2.2 on 2025-07-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0015_jsonresponsemaxi'),
    ]

    operations = [
        migrations.CreateModel(
            name='t011lan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfilcod', models.IntegerField(help_text='Código da Filial', verbose_name='NFilCod')),
                ('ncnpfor', models.IntegerField(help_text='CNPJ do fornecedor', verbose_name='NCnpFor')),
                ('snomfor', models.CharField(help_text='Nomde do Fornecedor', max_length=100, verbose_name='SNomFor')),
                ('ddatemi', models.DateField(help_text='Data de Emissão', max_length=100, verbose_name='DDatEmi')),
                ('ddatven', models.DateField(help_text='Data de Vencimento', max_length=100, verbose_name='DDatVen')),
                ('nvlrlan', models.DecimalField(decimal_places=2, help_text='Valor do Lançamento', max_digits=10, verbose_name='NVlrLan')),
                ('ncodsol', models.IntegerField(help_text='Código de Solicitação do ERP', verbose_name='NCodSol')),
                ('ncodcon', models.IntegerField(help_text='Código do Contrato', verbose_name='NCodCon')),
                ('ncodtra', models.IntegerField(help_text='Transação', verbose_name='NCodTra')),
                ('scodccu', models.CharField(help_text='Centro de Custo', max_length=9, verbose_name='SCodCcu')),
                ('sobslan', models.TextField(help_text='Observação', max_length=1000, verbose_name='SObsLan')),
            ],
            options={
                'db_table': 't011lan',
                'db_table_comment': 'Lançamentos de Contratos',
            },
        ),
    ]
