# Generated by Django 5.2.2 on 2025-08-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0016_t011lan'),
    ]

    operations = [
        migrations.CreateModel(
            name='t200ipc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssrvtag', models.CharField(help_text='Identificador do equipamento', max_length=50, verbose_name='SSrvTag')),
                ('snomset', models.CharField(help_text='Setor do Equipamento', max_length=100, verbose_name='SNomSet')),
                ('stipeqp', models.CharField(help_text='Tipo do Equipamento', max_length=100, verbose_name='STipEqp')),
                ('sipeend', models.CharField(help_text='Endereço IP do Equipamento', max_length=50, verbose_name='SIpeEnd')),
                ('smacend', models.CharField(help_text='Endereço Mac do Equipamento', max_length=100, verbose_name='SMacEnd')),
                ('smodeqp', models.CharField(help_text='Modelo do Equipamento', max_length=50, verbose_name='SModEqp')),
                ('sstteqp', models.CharField(help_text='Status de Conexão', max_length=5, verbose_name='SSttEqp')),
            ],
            options={
                'db_table': 't200ipc',
                'db_table_comment': 'Controle de Equipamentos por IP',
            },
        ),
    ]
