# Generated by Django 5.2.2 on 2025-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0017_t200ipc'),
    ]

    operations = [
        migrations.CreateModel(
            name='t002set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scodset', models.CharField(help_text='Abrev. Setor', max_length=5, verbose_name='SCodSet')),
                ('ssetnam', models.CharField(help_text='Nome do Setor', max_length=50, verbose_name='SSetNam')),
            ],
            options={
                'db_table': 't002set',
                'db_table_comment': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='t003tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scodtip', models.CharField(help_text='Abrev. Tipo', max_length=5, verbose_name='SCodTip')),
                ('stipnam', models.CharField(help_text='Nome do Tipo', max_length=50, verbose_name='STipNam')),
            ],
            options={
                'db_table': 't003tip',
                'db_table_comment': 'Tipos de Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='t004eqp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scodeqp', models.IntegerField(help_text='Código Equipamento', verbose_name='SCodEqp')),
                ('seqpnam', models.CharField(help_text='Nome do Equipamento', max_length=50, verbose_name='SEqpNam')),
            ],
            options={
                'db_table': 't004eqp',
                'db_table_comment': 'Equipamentos',
            },
        ),
    ]
