# Generated by Django 5.2.2 on 2025-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0018_t002set_t003tip_t004eqp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t100lic',
            name='slinsit',
            field=models.CharField(blank=True, help_text='Site da Licença', max_length=500, null=True, verbose_name='SLinSit'),
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='sobsadi',
            field=models.TextField(blank=True, help_text='Observação Adicional', max_length=1000, null=True, verbose_name='SObsAdi'),
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='ssencre',
            field=models.CharField(blank=True, help_text='Senha de acesso', max_length=100, null=True, verbose_name='SSenCre'),
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='ssernum',
            field=models.CharField(blank=True, help_text='Serial Number da Licença', max_length=200, null=True, verbose_name='SSerNum'),
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='ssetres',
            field=models.CharField(blank=True, help_text='Setor responsavel pela renovação', max_length=100, null=True, verbose_name='SSetRes'),
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='ssitlic',
            field=models.CharField(blank=True, help_text='Situação da Licença', max_length=20, null=True, verbose_name='SSitLic'),
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='susrcre',
            field=models.CharField(blank=True, help_text='Credencial de acesso', max_length=100, null=True, verbose_name='SUsrCre'),
        ),
    ]
