# Generated by Django 5.2.2 on 2025-08-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0019_alter_t100lic_slinsit_alter_t100lic_sobsadi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t100lic',
            name='slinsit',
            field=models.CharField(blank=True, default='N/A', help_text='Site da Licença', max_length=500, verbose_name='SLinSit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='sobsadi',
            field=models.TextField(blank=True, default='N/A', help_text='Observação Adicional', max_length=1000, verbose_name='SObsAdi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='ssencre',
            field=models.CharField(blank=True, default='N/A', help_text='Senha de acesso', max_length=100, verbose_name='SSenCre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='ssernum',
            field=models.CharField(blank=True, default='N/A', help_text='Serial Number da Licença', max_length=200, verbose_name='SSerNum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='ssetres',
            field=models.CharField(blank=True, default='N/A', help_text='Setor responsavel pela renovação', max_length=100, verbose_name='SSetRes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='ssitlic',
            field=models.CharField(blank=True, default='N/A', help_text='Situação da Licença', max_length=20, verbose_name='SSitLic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t100lic',
            name='susrcre',
            field=models.CharField(blank=True, default='N/A', help_text='Credencial de acesso', max_length=100, verbose_name='SUsrCre'),
            preserve_default=False,
        ),
    ]
