# Generated by Django 5.2.2 on 2025-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APT_Main', '0020_alter_t100lic_slinsit_alter_t100lic_sobsadi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='t300med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncoduni', models.IntegerField(help_text='Código Único', verbose_name='NCodUni')),
                ('sabrcon', models.CharField(help_text='Abreviatura da Conversão', max_length=20, verbose_name='SAbrCon')),
                ('sdescon', models.CharField(help_text='Descrição da Conversão', max_length=200, verbose_name='SDesCon')),
            ],
            options={
                'db_table': 't300med',
                'db_table_comment': 'Métodos de Conversão de Medidas',
            },
        ),
    ]
